# Generated by Django 3.1.1 on 2020-10-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='queue',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='refund.analysisqueue'),
        ),
    ]
