# Generated by Django 3.1.1 on 2020-10-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundbundle',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='refundbundle',
            name='pix',
        ),
    ]
