# Generated by Django 3.1.1 on 2020-10-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundbundle',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue', to='refund.paymentqueue'),
        ),
    ]
