# Generated by Django 3.1.1 on 2020-10-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('refund', '0002_auto_20201005_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='refundbundle',
            name='queue',
        ),
        migrations.AddField(
            model_name='refundbundle',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='refundbundle',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
