# Generated by Django 3.1.1 on 2020-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_auto_20201028_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundbundle',
            name='refund_memo',
            field=models.ImageField(upload_to='refund_memos'),
        ),
    ]
